DELETE FROM transactions; 
DELETE FROM historical_transactions;  
DELETE FROM plan_line_items;
DELETE FROM transaction_categories;
DELETE FROM accounting_categories;
DELETE FROM bank_accounts;
DELETE FROM assumption_id_sequence;


INSERT INTO accounting_categories
  (id, code, display_name, description, direction)
VALUES
  (1,  'CORE_REV',   '💰 Core Revenue',                'Primary income generated by the business, e.g. rental income for apartment complexes.', 'POSITIVE'),
  (2,  'OTHER_INC',  '💸 Other Income',               'Ancillary income such as parking fees, vending, or laundry revenue.',                  'POSITIVE'),
  (3,  'COGS',       '⚙️ Cost of Goods Sold',         'Direct costs related to the production of service or goods, or direct costs allocated to service delivery.', 'NEGATIVE'),
  (4,  'OPEX',       '🧾 Operating Expenses',         'Recurring daily expenses necessary to run the business such as salaries, utilities, and maintenance.',  'NEGATIVE'),
  (5,  'DEPR',       '📉 Depreciation/ Amortization', 'Non-cash expense representing the gradual consumption of fixed or intangible assets.',    'NEGATIVE'),
  (6,  'TAX',        '🏛️ Taxes',                      'Government or property-related tax expenses.',                                         'NEGATIVE'),
  (7,  'FIN',        '🏦 Financing Costs',            'Expenses related to financing such as interest and bank fees.',                        'NEGATIVE'),
  (8,  'OTHER_EXP',  '📦 Other Expenses / Miscellaneous', 'Any other operational expenses that do not fit in the above categories.',      'NEGATIVE'),
  (9,  'BORROW',     '💵 Borrowing',                  'Cash inflow from loans or credit lines.',                                             'POSITIVE'),
  (10, 'REPAY',      '💳 Repayment',                  'Cash outflow for loan repayments or credit line repayments.',                          'NEGATIVE');


INSERT INTO bank_accounts (id, account_number, currency, bank_name, owner) VALUES
  (1, '1234567890', 'HUF', 'OTP Bank', 'Apartment Complex Owner');

INSERT INTO assumption_id_sequence (seq_name, next_val) VALUES
  ('default', 1003);

INSERT INTO transaction_categories (id, name, accounting_category_id, direction, description)
VALUES
  (1, 'Apartment Rent', 1, 'POSITIVE', 'Monthly rent income from apartment units.'),
  (2, 'Parking Income', 2, 'POSITIVE', 'Income from parking fees.'),
  (3, 'Laundry Income', 2, 'POSITIVE', 'Income from the laundry machines.'),
  (4, 'Vending Income', 2, 'POSITIVE', 'Income from vending machines placed in common areas.'),
  (5, 'Staff Salary', 4, 'NEGATIVE', 'Salary expenses for administrative staff.'),
  (6, 'Gardener Salary', 4, 'NEGATIVE', 'Salary expense for the gardener.'),
  (7, 'Maintenance & Repairs', 8, 'NEGATIVE', 'Expenses for general maintenance and repair works.'),
  (8, 'Utilities', 8, 'NEGATIVE', 'Utility bills including electricity, water, and gas.'),
  (9, 'Property Taxes', 6, 'NEGATIVE', 'Annual or monthly property tax expenses.'),
  (10, 'Insurance Expense', 7, 'NEGATIVE', 'Payments for property and liability insurance.'),
  (11, 'Depreciation', 5, 'NEGATIVE', 'Non-cash expense to account for asset depreciation.'),
  (12, 'Financing Charges', 7, 'NEGATIVE', 'Interest expenses and bank fees.'),
  (13, 'Consumable Supplies', 3, 'NEGATIVE', 'Cost for supplies directly consumed in operations.'),
  (14, 'Miscellaneous Expense', 4, 'NEGATIVE', 'Miscellaneous expenses not categorized elsewhere.'),
  (15, 'Bank Loan Received', 9, 'POSITIVE', 'Proceeds from a bank loan for property financing.'),
  (16, 'Loan Repayment', 10, 'NEGATIVE', 'Scheduled repayment of loan principal and interest.');


-- TODO: add Unique index on (rate_date, base_currency, quote_currency) in exchange_rate table
-- INSERT INTO exchange_rate



  INSERT INTO transactions
  (account_id, booking_date, value_date, partner_name, partner_account_number, amount, currency,  transaction_type, transaction_code, category_id, memo, transaction_method)
VALUES
(1, '2024-01-05', '2024-01-05', 'Tenant 1', 'UNIT01', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R1', 1, 'Monthly rent for Unit 1', 'TRANSFER'),
(1, '2024-01-05', '2024-01-05', 'Tenant 2', 'UNIT02', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R2', 1, 'Monthly rent for Unit 2', 'TRANSFER'),
(1, '2024-01-05', '2024-01-05', 'Tenant 3', 'UNIT03', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R3', 1, 'Monthly rent for Unit 3', 'TRANSFER'),
(1, '2024-01-05', '2024-01-05', 'Tenant 4', 'UNIT04', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R4', 1, 'Monthly rent for Unit 4', 'TRANSFER'),
(1, '2024-01-05', '2024-01-05', 'Tenant 5', 'UNIT05', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R5', 1, 'Monthly rent for Unit 5', 'TRANSFER'),
(1, '2024-01-05', '2024-01-05', 'Tenant 6', 'UNIT06', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R6', 1, 'Monthly rent for Unit 6', 'TRANSFER'),
(1, '2024-01-05', '2024-01-05', 'Tenant 7', 'UNIT07', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R7', 1, 'Monthly rent for Unit 7', 'TRANSFER'),
(1, '2024-01-05', '2024-01-05', 'Tenant 8', 'UNIT08', 200000.00, 'HUF', 'POSITIVE', 'TR-2024-01-R8', 1, 'Monthly rent for Unit 8', 'TRANSFER'),
(1, '2024-01-06', '2024-01-06', 'Parking Income', 'PARK01', 50000.00, 'HUF', 'POSITIVE', 'TR-2024-01-P1', 2, 'Parking income', 'TRANSFER'),
(1, '2024-01-06', '2024-01-06', 'Parking Income', 'PARK02', 50000.00, 'HUF', 'POSITIVE', 'TR-2024-01-P2', 2, 'Parking income', 'TRANSFER'),
(1, '2024-01-07', '2024-01-07', 'Laundry Income', 'LAUN01', 30000.00, 'HUF', 'POSITIVE', 'TR-2024-01-L1', 3, 'Laundry income', 'TRANSFER'),
(1, '2024-01-07', '2024-01-07', 'Laundry Income', 'LAUN02', 30000.00, 'HUF', 'POSITIVE', 'TR-2024-01-L2', 3, 'Laundry income', 'TRANSFER'),
(1, '2024-01-08', '2024-01-08', 'Vending Income', 'VEND01', 25000.00, 'HUF', 'POSITIVE', 'TR-2024-01-V1', 4, 'Vending income', 'TRANSFER'),
(1, '2024-01-08', '2024-01-08', 'Vending Income', 'VEND02', 25000.00, 'HUF', 'POSITIVE', 'TR-2024-01-V2', 4, 'Vending income', 'TRANSFER'),
(1, '2024-01-10', '2024-01-10', 'Misc Income', 'MISC01', 10000.00, 'HUF', 'POSITIVE', 'TR-2024-01-MI1', 2, 'Miscellaneous income', 'TRANSFER'),
(1, '2024-01-11', '2024-01-11', 'Misc Income', 'MISC02', 15000.00, 'HUF', 'POSITIVE', 'TR-2024-01-MI2', 2, 'Miscellaneous income', 'TRANSFER'),
(1, '2024-01-12', '2024-01-12', 'Misc Income', 'MISC03', 20000.00, 'HUF', 'POSITIVE', 'TR-2024-01-MI3', 2, 'Miscellaneous income', 'TRANSFER'),
(1, '2024-01-13', '2024-01-13', 'Misc Income', 'MISC04', 25000.00, 'HUF', 'POSITIVE', 'TR-2024-01-MI4', 2, 'Miscellaneous income', 'TRANSFER'),
(1, '2024-01-14', '2024-01-14', 'Misc Income', 'MISC05', 30000.00, 'HUF', 'POSITIVE', 'TR-2024-01-MI5', 2, 'Miscellaneous income', 'TRANSFER'),
(1, '2024-01-15', '2024-01-15', 'Staff 1', 'STF01', 300000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-SS1', 5, 'Staff salary for Staff 1', 'TRANSFER'),
(1, '2024-01-15', '2024-01-15', 'Staff 2', 'STF02', 300000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-SS2', 5, 'Staff salary for Staff 2', 'TRANSFER'),
(1, '2024-01-16', '2024-01-16', 'Gardener', 'GRD', 150000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-GS', 6, 'Gardener salary', 'TRANSFER'),
(1, '2024-01-20', '2024-01-20', 'Maintenance Co.', 'MAINT', 350000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-MR', 7, 'Maintenance & Repairs', 'TRANSFER'),
(1, '2024-01-22', '2024-01-22', 'Electric Company', 'ELEC', 60000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-UT1', 8, 'Electricity bill', 'TRANSFER'),
(1, '2024-01-23', '2024-01-23', 'Water Company', 'WATR', 40000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-UT2', 8, 'Water bill', 'TRANSFER'),
(1, '2024-01-28', '2024-01-28', 'Tax Dept.', 'TAX', 90000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-PT', 9, 'Property taxes', 'TRANSFER'),
(1, '2024-01-29', '2024-01-29', 'Insurance Co.', 'INS', 60000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-IN', 10, 'Insurance expense', 'TRANSFER'),
(1, '2024-01-30', '2024-01-30', 'Depreciation', 'DEPR', 25000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-DP', 11, 'Depreciation expense', 'TRANSFER'),
(1, '2024-01-31', '2024-01-31', 'Bank Fees', 'BANK', 40000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-FC', 12, 'Financing charges', 'TRANSFER'),
(1, '2024-01-18', '2024-01-18', 'Supply Vendor', 'SUP01', 30000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-CS1', 13, 'Consumable supplies', 'TRANSFER'),
(1, '2024-01-19', '2024-01-19', 'Supply Vendor', 'SUP02', 35000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-CS2', 13, 'Consumable supplies', 'TRANSFER'),
(1, '2024-01-26', '2024-01-26', 'Misc Expense', 'ME01', 5000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME1', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-26', '2024-01-26', 'Misc Expense', 'ME02', 6000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME2', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-27', '2024-01-27', 'Misc Expense', 'ME03', 7000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME3', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-27', '2024-01-27', 'Misc Expense', 'ME04', 8000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME4', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-28', '2024-01-28', 'Misc Expense', 'ME05', 9000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME5', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-28', '2024-01-28', 'Misc Expense', 'ME06', 10000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME6', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-29', '2024-01-29', 'Misc Expense', 'ME07', 11000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME7', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-29', '2024-01-29', 'Misc Expense', 'ME08', 12000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME8', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-30', '2024-01-30', 'Misc Expense', 'ME09', 13000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME9', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-30', '2024-01-30', 'Misc Expense', 'ME10', 14000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME10', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-31', '2024-01-31', 'Misc Expense', 'ME11', 15000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME11', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-31', '2024-01-31', 'Misc Expense', 'ME12', 16000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME12', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-31', '2024-01-31', 'Misc Expense', 'ME13', 17000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME13', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-31', '2024-01-31', 'Misc Expense', 'ME14', 18000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME14', 14, 'Miscellaneous expense', 'TRANSFER'),
(1, '2024-01-31', '2024-01-31', 'Misc Expense', 'ME15', 19000.00, 'HUF', 'NEGATIVE', 'TR-2024-01-ME15', 14, 'Miscellaneous expense', 'TRANSFER');